---
title: "Classification based machine learning for trading in R"
output: html_notebook
---
 
 Loading data and calculation of moving averages

```{r, warning = FALSE}
library(tidyverse)
library(lubridate)
library(quantmod)
library(depmixS4)

#Loading the data
price <- read.csv("wtiDaily.csv")

#Custom function to be able to change the data into an xts format
setup_data <- function(pricedata) {
  
       names(pricedata) <- c("Date", "Open", "High", "Low", "Close")
       dates <- parse_date_time(x = pricedata[,1], "mdy_HM", truncated = 3)
       pricedata <- pricedata[,2:5]
       pricedata <- xts(pricedata, order.by = dates)
}


price <- setup_data(price)
ema7 <- EMA(price$Close, n = 7)
ema20 <- EMA(price$Close, n = 20)
ema50 <- EMA(price$Close, n = 50)
ema70 <- EMA(price$Close, n = 70)
ema140 <- EMA(price$Close, n = 140)
priceEma.20.Diff <- price$Close - ema20

```

### Plotting the data since June 2017

```{r}
chartSeries(price, TA=NULL, subset = '2017-12::', theme = "white")
addEMA(n = 7,col = "orange")
addEMA(n = 20,col = "red")

```

###Feature engineering and predictior variables
Defining the type of candle (features) and dataframe to use for learning purpose

```{r}

feat.eng <- function(pricedata, emafast, emaslow) { 
candle.type.today <- data.frame(ifelse( pricedata$Close > pricedata$Open, "1", "0"))
candle.type.past1days <- data.frame(lag(candle.type.today$Close, n = 1))
candle.type.nextday <- data.frame(lead(candle.type.today$Close, n = 1))
close.to.emafast <- data.frame(ifelse(pricedata$Close > emafast, "1", "0"))
close.to.emaslow <- data.frame(ifelse(pricedata$Close > emaslow, "1", "0"))
emafast.to.emaslow <- data.frame(ifelse(emafast > emaslow, "1", "0"))
dailywin <- data.frame(abs(pricedata$Close - pricedata$Open))
candle.nextday.win <- lead(dailywin$Close, 1)
dailyprice <- data.frame(candle.type.today,candle.type.past1days, close.to.emafast, close.to.emaslow, emafast.to.emaslow, dailywin, candle.nextday.win, candle.type.nextday)
names(dailyprice) <- c("candle.type.current", "candle.type.past1days", "close.to.emafast", "close.to.emaslow", "emafast.to.emaslow", "dailywin", "candle.nextday.win", "candle.type.nextday")
return(dailyprice)
}

#Add Hidden markov model data
set.seed(1)
hmmdata <- data.frame(priceEma.20.Diff[-c(1:21),])
HMM <- depmix(hmmdata$Close ~ 1, data = hmmdata, nstates = 3, family = gaussian())
hmmfit <- fit(HMM, verbose = FALSE)

post_probs <- posterior(hmmfit)

#data being feature engineered
dailyprice <- feat.eng(price, ema7, ema20)
dailyprice <- slice(dailyprice, 22:length(dailyprice$candle.type.current))
dailyprice$state <- post_probs[,1]


plot(price$Close[426:536,])

```

          
### Training and testing formatting

```{r}
train <- dailyprice[1:300,]
test <- dailyprice[301:516,]


#function for processing predictions
predictedReturn <- function(df, pred){
    df$pred <- pred
    df$prediReturn <- ifelse(df$candle.type.nextday != df$pred, -df$candle.nextday.win, df$candle.nextday.win)
    df$cumReturn <- cumsum(df$prediReturn)
    return(df)    
}


plot(price$Close[320:536,])  
```
```{r, message= FALSE}

library(keras)

x_train <- as.matrix(train[,-(7:8)])
y_train <- as.matrix(train[,8])
x_test <- as.matrix(test[1:215,-(7:8)])
y_test <- as.matrix(test[1:215,8])

model <- keras_model_sequential() %>%
  layer_dense(units = 20, activation = "relu", input_shape = c(7)) %>%
  layer_dense(units = 20, activation = "relu") %>%
  layer_dense(units = 16, activation = "relu") %>%
  layer_dense(units = 16, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")
#
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
   metrics = c("accuracy")
 )

history <- model %>% fit(
  x_train,
  y_train,
   epochs = 50,
   batch_size = 50,
   validation_data = list(x_test, y_test)
 )
#
 results <- model %>% evaluate(x_test, y_test)

model %>% save_model_hdf5("deepLearningModel_ClDaily.h5")
# results
#
dp.predi <- model %>% predict(x_test)
dp.predi <- ifelse(dp.predi < 0.5, 0, 1)

dl.test <- predictedReturn(test[1:215,], dp.predi)

```

Plots

```{r}
plot(dl.test$prediReturn, type = "line")
plot(dl.test$cumReturn, type = "line")

dl.misclsserror <- mean(dl.test$candle.type.nextday != dl.test$pred)
print(paste("Accuracy", 1-dl.misclsserror))
```

## Test of jul to Nov 18 data

```{r}
library(depmixS4)
price_jul_nov18 <- read.csv("jul-nov18.csv")

price_jul_nov18 <- setup_data(price_jul_nov18)
ema7 <- EMA(price_jul_nov18$Close, n = 7)
ema20 <- EMA(price_jul_nov18$Close, n = 20)
ema50 <- EMA(price_jul_nov18$Close, n = 50)
ema70 <- EMA(price_jul_nov18$Close, n = 70)
priceEma20Diff.julNov18 <- price_jul_nov18$Close - ema20

price_jul_nov18 <- feat.eng(price_jul_nov18, ema7, ema20)

#Add Hidden markov model data
hmmdata.julNov18 <- data.frame(priceEma20Diff.julNov18[-c(1:21),])
HMM.julNov18  <- depmix(hmmdata.julNov18$Close ~ 1, data = hmmdata.julNov18, nstates = 3, family = gaussian())
hmmfit.julNov18  <- fit(HMM.julNov18, verbose = FALSE)
post_probs.julNov18 <- posterior(hmmfit.julNov18)

jul_nov18_test <- price_jul_nov18[-(1:21),]
jul_nov18_test$state <- post_probs.julNov18[,1]


jul_nov18_test <- as.matrix(jul_nov18_test[,-(7:8)])



new.predi <- model %>% predict(jul_nov18_test)
new.predi <- ifelse(new.predi < 0.5, 0, 1)

new.test <- predictedReturn(price_jul_nov18[-(1:21),], new.predi)

plot(new.test$prediReturn, type = "line")
plot(new.test$cumReturn, type = "line")

plot(hmmdata.julNov18$Close, type='l', main='Regime Detection', xlab='', ylab='Returns')
matplot(post_probs.julNov18[,-1], type='l', main='Regime Posterior Probabilities', ylab='Probability')
legend(x='bottomleft', c('Regime #1','Regime #2', 'Regime #3'), fill=1:3, bty='n')

```

