---
title: "Daily data ML for crude oil"
output: html_notebook
---
 
 Loading data and calculation of moving averages

```{r}


library(tidyverse)
library(lubridate)
library(quantmod)
library(ggplot2)

price <- read.csv("wtiDaily.csv")

setup_data <- function(pricedata) {
  
       names(pricedata) <- c("Date", "Open", "High", "Low", "Close")
       dates <- parse_date_time(x = pricedata[,1], "mdy_HM", truncated = 3)
       pricedata <- pricedata[,2:5]
       pricedata <- xts(pricedata, order.by = dates)
}


price <- setup_data(price)
ema7 <- EMA(price$Close, n = 7)
ema20 <- EMA(price$Close, n = 20)
ema50 <- EMA(price$Close, n = 50)
ema70 <- EMA(price$Close, n = 70)

```



```{r}
chartSeries(price, TA=NULL, subset = '2017-06::')
addEMA(n = 7,col = "orange")
addEMA(n = 20,col = "red")
#addEMA(n = 70,col = "blue")


```

Defining the type of candle (features) and dataframe to use for learning purpose

```{r}
#Defining the individual features/variables
candle.type.current <- data.frame(ifelse( price$Close > price$Open, "bull", "bear"))
candle.type.previous <- data.frame(lag(candle.type.current$Close, n = 1))
candle.next.day <- data.frame(lead(candle.type.current$Close, n = 1))
doji <- data.frame(ifelse(abs(price$Close - price$Open) <= 0.45, "yes", "no"))
position.to.ema7 <- data.frame(ifelse(price$Close > ema7, "above", "below"))
position.to.ema20 <- data.frame(ifelse(price$Close > ema20, "above", "below"))
ema7.to.ema20 <- data.frame(ifelse(ema7 > ema20, "above", "below"))
dailywin <- data.frame(abs(price$Close - price$Open))
candle.nextday.win <- lead(dailywin$Close, 1)

#Making up the dataframe with all the features as columns
dailyprice <- data.frame(candle.type.current,candle.type.previous,
                         doji, position.to.ema7,position.to.ema20, 
                         ema7.to.ema20, dailywin, candle.nextday.win,
                         candle.next.day)

# naming the dataframe columns
names(dailyprice) <- c("candle.type.current", "candle.type.previous",
                       "doji", "position.to.ema7", "position.to.ema20",
                       "ema7.to.ema20", "dailywin", "candle.nextday.win", 
                       "candle.next.day")

#selecting the data with no NAs
dailyprice <- slice(dailyprice, 21:length(dailyprice$doji))

```

Data preparation and partitioning

```{r}

#Splitting the data into training and testing (time slice)
testRange <- 71:400
trainRange <- 1:70
test <- dailyprice[testRange,]
train <- dailyprice[trainRange,]

#Defining the formula: Target variables and predictors
target <- "candle.next.day"
predictors.variable <- c("candle.type.current", "candle.type.previous",
                         "doji", "position.to.ema7", "position.to.ema20",
                         "ema7.to.ema20", "dailywin")

predictors <- paste(predictors.variable, collapse = "+")
formula <- as.formula(paste(target, "~", predictors, sep = ""))



#function for processing predictions
predictedReturn <- function(df, pred){
    df$pred <- pred
    df$prediReturn <- ifelse(df$candle.next.day != df$pred, -df$candle.nextday.win, df$candle.nextday.win)
    df$cumReturn <- cumsum(df$prediReturn)
    return(df)
}


plot(price$Close[91:536,])
```


## Support vector machine

```{r}
library("e1071")

#Creating the support vector machine model
modelsvm <- svm(formula, data = train, kernel = "radial", cost =10, gamma = 0.2) 

# Prediction
pred.svm <- predict(modelsvm, test)
#pred.svm <- ifelse(pred.glm > 0.5, "1", "0")

summary(modelsvm)

#Put dummy values for the last day of data (svm does not handle NAs)
test$candle.next.day <- replace_na(test$candle.next.day, replace = "bull")
test$dailywin <- replace_na(test$dailywin, replace = 0.5)

#Results
svm.test <- predictedReturn(test, pred.svm)

#Plot daily returns and cummulative returns
plot(svm.test$prediReturn)
plot(svm.test$cumReturn, type = "line")
confusionMatrix.svm <- table(svm.test$candle.next.day, svm.test$pred)
print(confusionMatrix.svm)

#calculating the accuracy
svm.misclsserror <- mean(svm.test$candle.next.day != svm.test$pred)
print(paste("Accuracy", 1-svm.misclsserror))

```



